# Generated by Django 4.2.7 on 2023-11-27 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('discription', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.CharField(max_length=100)),
                ('foldres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.folder')),
            ],
        ),
        migrations.AddField(
            model_name='folder',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.users'),
        ),
    ]
